FROM node:20-alpine
WORKDIR /app

# Copy dependencies first for better caching
COPY package*.json ./
RUN npm install

# Copy the rest of your code
COPY . .


EXPOSE 9000

# Start the development server
CMD ["npm", "run", "dev"]